using System;

namespace DHI.MPSOPS.DOMAIN.Model
{
    public class Order
    {
        public int OrderId { get; set; }
        public DateTime OrderDate { get; set; }
        public TimeSpan OrderTimeSpan { get; set; }
        public string Caller { get; set; }
        public string CustomerId { get; set; }
        public string DelId { get; set; }
        public string Puid { get; set; }
        public string ServiceLevel { get; set; }
        public int OT { get; set; }
        public bool RT { get; set; }
        public string Reference { get; set; }
        public string UnitType { get; set; }
        public int Pieces { get; set; }
        public int WaitingTime { get; set; }
        public int Skids { get; set; }
        public decimal Rate { get; set; }
        public int Pounds { get; set; }
        public string Notes { get; set; }
        public string Ticket { get; set; }
        public bool NoCharge { get; set; }
        public int SplTotal { get; set; }
        public bool Processed { get; set; }
        public decimal Custom { get; set; }
        public DateTime PuDate { get; set; }
        public TimeSpan PuTime { get; set; }
        public bool Nload { get; set; }
        public bool MCDisc { get; set; }
        public DateTime Acknowledge { get; set; }
        public DateTime Onboard { get; set; }
        public DateTime Done { get; set; }
        public int DriveId { get; set; }
        public string Pod { get; set; }
        public string Contact { get; set; }
        public bool Print { get; set; }
        public string Chit { get; set; }
        public decimal Go { get; set; }
        public double DrComa { get; set; }
        public double OverWeight { get; set; }
        public double OverWait { get; set; }
        public double Overunit { get; set; }
        public int Drsub { get; set; }
        public double OverSkid { get; set; }
        public string CustId { get; set; }
        public decimal Codamt { get; set; }
        public string PuContact { get; set; }
        public string DelContact { get; set; }
        public DateTime DoneDate { get; set; }
        public string PodOrder { get; set; }
        public string Courier { get; set; }
        public string CourierJob { get; set; }
        public string Spare1 { get; set; }
        public string Spare2 { get; set; }
        public DateTime DeliveryDate { get; set; }
        public TimeSpan DeliveryTime { get; set; }
        public string Manifestnum { get; set; }
        public bool ResDelivery { get; set; }
        public bool ResPu { get; set; }
        public bool WharfDel { get; set; }
        public bool MenDel { get; set; }
        public bool MenPu { get; set; }
        public bool AirPtDel { get; set; }
        public bool InsideDel { get; set; }
        public bool InsidePu { get; set; }
        public bool LiftGtDel { get; set; }
        public bool LiftGtPu { get; set; }
        public bool PalletDel { get; set; }
        public bool HotelDel { get; set; }
        public bool UnCrate { get; set; }
        public bool DeTrash { get; set; }
        public bool CodFee { get; set; }
        public bool TransferChg { get; set; }
        public bool MilitaryDel { get; set; }
        public bool MilitaryPu { get; set; }
        public bool HrWindow { get; set; }
        public bool SalesTax { get; set; }
        public bool PalletPu { get; set; }
        public string EnteredBy { get; set; }
        public int Route { get; set; }
        public bool SpecialRate { get; set; }
        public bool Banking { get; set; }
        public string ManCode { get; set; }
        public DateTime ReturnTime { get; set; }
        public int HHSent { get; set; }
        public bool HazMat1 { get; set; }
        public bool HazMat { get; set; }
        public string OrderType { get; set; }
        public bool NoSigRequired { get; set; }
        public string AutoPodEmailAddress { get; set; }
        public bool AutoPodSent { get; set; }
        public DateTime AssignedTime { get; set; }
        public string BillOfLading { get; set; }
        public decimal CourierWaiting { get; set; }
        public string VendorNotes { get; set; }
        public bool ShipOutOrder { get; set; }
        public int Shift { get; set; }
        public int OriginalPkg { get; set; }
        public int PuPkGCount { get; set; }
        public int DeliveryPkgCount { get; set; }

        public bool BarcodeScanRequired { get; set; }
        public DateTime BillDate { get; set; }
        public int RouteNum { get; set; }
        public string Reference2 { get; set; }
        public int ExportStatus { get; set; }
        public int VersionNum { get; set; }
        public string PickupRemark { get; set; }
        public string DeliveryRemark { get; set; }
        public int PcsDelivered { get; set; }
        public bool Delivered { get; set; }

    }
}